"""empty message

Revision ID: 51df084b602d
Revises: f1592d573d59
Create Date: 2020-05-31 21:46:18.443230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51df084b602d'
down_revision = 'f1592d573d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('date_show', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'date_show')
    # ### end Alembic commands ###
