"""empty message

Revision ID: 832553ccc264
Revises: f892560e2ec3
Create Date: 2020-06-01 15:26:28.300729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832553ccc264'
down_revision = 'f892560e2ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.drop_column('venue', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genre', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###
