"""empty message

Revision ID: f892560e2ec3
Revises: 1a8960782c73
Create Date: 2020-06-01 14:32:29.475831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f892560e2ec3'
down_revision = '1a8960782c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
